import { defineStore } from 'pinia'

export const useUserStore = defineStore('user', {
    state: () => ({

        name: '鱼鱼蒸饭了',
        signature: "人一旦失去重要的东西，就很难再获得了",
        avatar:'https://pic.imgdb.cn/item/65f271609f345e8d03f68b71.jpg',
        aphorism:'What a marvelous thing we lose?',
        e_mail:'1427702848@qq.com',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    }),
    actions: {
        // ...
    }
})